# Generated by Django 5.1.4 on 2025-01-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_materia_progressomateria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressomateria',
            old_name='questoes_concluidas',
            new_name='idQuestoesFeitas',
        ),
    ]
