# Generated by Django 5.1.4 on 2025-01-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_quizresponse'),
        ('users', '0006_rename_questoes_concluidas_progressomateria_idquestoesfeitas'),
    ]

    operations = [
    ]
