# Generated by Django 5.1.4 on 2025-01-30 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_quizresponse'),
        ('users', '0006_rename_questoes_concluidas_progressomateria_idquestoesfeitas'),
    ]

    operations = [
    ]
