# Generated by Django 5.1.4 on 2025-02-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_quizresponse'),
        ('users', '0007_merge_20250125_1852'),
    ]

    operations = [
    ]
