# Generated by Django 5.1.4 on 2025-02-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20250129_2130'),
        ('users', '0009_profile'),
    ]

    operations = [
    ]
