# Generated by Django 5.1.4 on 2025-02-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20250128_0950'),
        ('users', '0011_alter_profile_image'),
    ]

    operations = [
    ]
